openapi: 3.0.1
info:
  title: api
  version: ''
  description: This API is part of Toku Assignment for Senior Engineer Interview.
paths:
  /consumer/simulate:
    post:
      description: Queue N simulations of fights between 2 heroes
      operationId: heroSim_runSimulation
      tags:
        - HeroSim
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RunSimulationResponse'
        '400':
          description: ''
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      error:
                        type: string
                        enum:
                          - InvalidRequestError
                      content:
                        $ref: '#/components/schemas/ErrorBody'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                numSimulations:
                  type: integer
              required:
                - numSimulations
components:
  schemas:
    RunSimulationResponse:
      title: RunSimulationResponse
      type: object
      properties:
        startId:
          type: integer
          description: The id of the first simulation job created
        endId:
          type: integer
          description: The id of the last simulation job created
      required:
        - startId
        - endId
    ErrorBody:
      title: ErrorBody
      type: object
      properties:
        errorMessage:
          type: string
      required:
        - errorMessage
  securitySchemes: {}
